# Generated by Django 3.2.12 on 2022-05-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_id',
            new_name='id',
        ),
    ]
