# Generated by Django 3.2.12 on 2022-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_rename_survey_id_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
