# Generated by Django 3.2.12 on 2022-06-01 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 11, 8, 24, 355614, tzinfo=utc)),
        ),
    ]
