# Generated by Django 3.2.12 on 2022-06-01 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
