# Generated by Django 4.0.4 on 2022-05-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
